// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0N0gtsQrmi-balXdHY3pceKZeRvqGWIo',
    appId: '1:524279931525:web:6441213ca2d5e9b5b7ffec',
    messagingSenderId: '524279931525',
    projectId: 'intership-manager',
    authDomain: 'intership-manager.firebaseapp.com',
    storageBucket: 'intership-manager.firebasestorage.app',
    measurementId: 'G-W1VF3HRY3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeOXxVwuBCNvp7evKYgbTRLxBu0dgqd9Q',
    appId: '1:524279931525:android:2116845f1201013bb7ffec',
    messagingSenderId: '524279931525',
    projectId: 'intership-manager',
    storageBucket: 'intership-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5PniOWitr4l2EPlQq9_yajhTZf6bTxdA',
    appId: '1:524279931525:ios:35a65097d465effeb7ffec',
    messagingSenderId: '524279931525',
    projectId: 'intership-manager',
    storageBucket: 'intership-manager.firebasestorage.app',
    iosBundleId: 'com.example.intershipManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5PniOWitr4l2EPlQq9_yajhTZf6bTxdA',
    appId: '1:524279931525:ios:35a65097d465effeb7ffec',
    messagingSenderId: '524279931525',
    projectId: 'intership-manager',
    storageBucket: 'intership-manager.firebasestorage.app',
    iosBundleId: 'com.example.intershipManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0N0gtsQrmi-balXdHY3pceKZeRvqGWIo',
    appId: '1:524279931525:web:db2f951916e2a43bb7ffec',
    messagingSenderId: '524279931525',
    projectId: 'intership-manager',
    authDomain: 'intership-manager.firebaseapp.com',
    storageBucket: 'intership-manager.firebasestorage.app',
    measurementId: 'G-DQ98CML2GV',
  );

}